var canvas = document.getElementById("canvas");
var ctx = canvas.getContext("2d");
var WIDTH = 600;
var HEIGHT = 600;
var TILE_SIZE = 40;
var life = 5;
var GameOver = false;
var gold = 0;
var fireCount = 0;
var MapNumber = 1;
var MaxMapNumber = 2;
var Reset = false;
var PlayerPower;
var UsedBLockSrc;
var rotating = false;
var condition = true;
var j = 1;
var k = true;
var l = true;
var m = 35;
var n = 0;